### ISSUE TITLE
How to manually make slider go to a value?

### ISSUE THREAD

**Issue by Pranoy1c** [varunpm1/VPRangeSlider#7]
How do i update the slider to go to a value?

Similar to how UISlider has setValue. How to set the min and max values?

**Comment by Pranoy1c** [comment]
the `scrollStartSliderToStartRange` doesn't seem to work if we manually call that

**Comment by varunpm1** [comment]
Hi @Pranoy1c ,

How did you call the `scrollStartSliderToStartRange` function? Remember that it should be in percentage (0-100) and start and end range should have at least separator width difference in between them.

**Comment by varunpm1** [comment]
Closing this issue since there is no further discussion. Let me know if this issue still persists
