### ISSUE TITLE
Slider Thumb Overlaps

### ISSUE THREAD

**Issue by vishaldeshai** [varunpm1/VPRangeSlider#8]
Hello Sir,

Can we Overlaps both the thumbs at same position or value.

i have time Slider with 00 to 24 value, i need to min and max value overlaps like 24:00 to 24:00.

Thanks in advance.

**Comment by varunpm1** [comment]
Hi,

If you're using normal Slider, you can make use of sliderSepertorWidth and set it to 0.

If you're using segment slider, then I have not added support for that feature.

Let me know if you want it in segmented slider

**Comment by vishaldeshai** [comment]
Yes sir, i need  in segmented Slider.

thanks.

**Comment by vishaldeshai** [comment]
is it possible?

**Comment by varunpm1** [comment]
Sorry for the late reply. As of now I haven't added support for that. I'll add it as soon as possible.

**Comment by varunpm1** [comment]
Hi Vishal,

I have added support for overlap in segmented slider view. You can make use of `shouldSliderButtonOverlap` to set to `YES` to overlap.

I'm closing this issue. Feel free to create new issue if further customization is needed.

Thanks
