### ISSUE TITLE
scrollStartSliderToStartRange:andEndRange: does not layout the range slider

### ISSUE THREAD

**Issue by 0rangeZ3r0** [varunpm1/VPRangeSlider#9]
Hello, I'm currently using the scrollStartSliderToStartRange:andEndRange: code to attempt and "reset" the range slider, but the range slider doesn't seem to go scroll back.

I currently have a button to reset the range slider's positions, when I run it in debug mode, it sets the min and max range to 0 and 100 respectively, but doesn't seem to reload the view of the range slider back to 0 and 100

The line of code I'm using currently looks like this:
`- (IBAction)onResetRangeBtnTouched:(id)sender {
      [self.rangeSlider scrollStartSliderToRange:0 andEndRange:100];
}`

**Comment by 0rangeZ3r0** [comment]
I will be closing this thread as there has been no response.

**Comment by varunpm1** [comment]
@0rangeZ3r0 , Apologies for the delayed response. I have been away and wasn't keeping track of GitHub. I'm available now. Let me know if you want me to look into this or if the issue has been resolved.

**Comment by 0rangeZ3r0** [comment]
I still have not resolved the issue, and have replaced the VPRangeSlider with another Range Slider. Thank you for the reply regardless.
